### PR TITLE
styling issues

### PR DESCRIPTION
**Pull request by lazarusA**
Hi, great package!

I'm adding some things that might improve the overall theme. 

1. Better grouping of elements in main menu, currently it overflows a lot to the right in normal screens. Here, some essential sections now go into a `Manual` category.
2. We match the theme colours with the ones in the logo
3. We use the fira code fonts, so that the pipe `|>` looks like that, not ligatures. 
4. we delete and ignore the `package-lock.json` file, is not needed. 
5. upgrade to latest vitepress

### CODE REVIEW

**Comment by svilupp** [comment]
Amazing! Thank you so much!

I’m travelling but I’ll try it tonight

**Review by svilupp — APPROVED** [review]
Really cool, stuff! I just previewed it and it looks great :)

**Comment by lazarusA** [comment]
oh, I didn't update the docs CI, hopefully latest commit will be enough. Otherwise we might also need the `DOCUMENTER_KEY`.

**Comment by svilupp** [comment]
DOCUMENTER_KEY is set as a repository secret, so hopefully that part should work.

**Comment by svilupp** [comment]
Thank you so much for the PR!

**Pull request merged**
