### PR TITLE
An issue for the gemini model + a proposed resolution

### PR DESCRIPTION
**Pull request by Muhammad-saad-2000**
Hello @svilupp,

## Context
I'm Mohammed Saad, a recent Computer Engineering graduate from Cairo University specializing in deep learning and machine learning.

I'm highly interested in this library, recognizing its potential in the evolving LLM landscape. A Julia-based LangChain-like solution would be incredibly valuable.

As of my plan to apply for julia at GSoC 2024 (JSoC), specifically the ColBERT project, I've been familiarizing myself with the PromptingTools.jl package.

## Problem
While I was doing some experiments, I stumbled upon an issue while running the provided example of gemini:
#### Clone the repository
```bash 
git clone https://github.com/svilupp/PromptingTools.jl.git
```
#### Prepare the dependencies
``` julia
import Pkg;
Pkg.activate(".")
Pkg.instantiate()
using Pkg; Pkg.add(url="https://github.com/tylerjthomas9/GoogleGenAI.jl/")
```
#### Running the provided example 
``` julia
using PromptingTools
const PT = PromptingTools

ENV["GOOGLE_API_KEY"] = "🤫"
msg = aigenerate("Say Hi!"; model="gemini")
```
#### Running an additional trial
``` julia
using PromptingTools
const PT = PromptingTools
using GoogleGenAI

ENV["GOOGLE_API_KEY"] = "🤫"
msg = aigenerate("Say Hi!"; model="gemini")
```

#### I faced the following error for both cases
```text
ArgumentError: You need to also import GoogleGenAI package to use this function

Stacktrace:
 [1] aigenerate(prompt_schema::PromptingTools.GoogleSchema, prompt::String; verbose::Bool, api_key::String, model::String, return_all::Bool, dry_run::Bool, conversation::Vector{PromptingTools.AbstractMessage}, http_kwargs::@NamedTuple{retry_non_idempotent::Bool, retries::Int64, readtimeout::Int64}, api_kwargs::@NamedTuple{}, kwargs::@Kwargs{})
   @ PromptingTools [~/🤫/PromptingTools.jl/src/llm_google.jl:163](https://file+.vscode-resource.vscode-cdn.net/🤫/PromptingTools.jl/~/🤫/PromptingTools.jl/src/llm_google.jl:163)
 [2] aigenerate(prompt::String; model::String, kwargs::@Kwargs{})
   @ PromptingTools [~/🤫/PromptingTools.jl/src/llm_interface.jl:263](https://file+.vscode-resource.vscode-cdn.net/🤫/PromptingTools.jl/~/🤫/PromptingTools.jl/src/llm_interface.jl:263)
 [3] top-level scope
   @ [~🤫/PromptingTools.jl/Experiments.ipynb:6](https://file+.vscode-resource.vscode-cdn.net/🤫/PromptingTools.jl/~/🤫/PromptingTools.jl/Experiments.ipynb:6)
```

## My thoughts
The core problem is the incorrect loading of the GoogleGenAIPromptingToolsExt.jl library. After investigating how the library works, I made multiple attempts to cleanly integrate the GoogleGenAIPromptingToolsExt module. These failed mainly because the GoogleGenAI.jl package is not yet registered in JuliaHub. This led me to question the necessity of using the extension module and GoogleGenAI.jl altogether. Ultimately, I resolved the issue by bypassing these packages and making the necessary additions directly within llm_google.jl (as detailed in my pull request).

#### Running this test
``` julia
using PromptingTools

ENV["GOOGLE_API_KEY"] = "🤫"
msg = aigenerate("Say Hi!"; model="gemini")
```
#### Gives this output
```text
┌ Info: Tokens: 206 in 6.8 seconds
└ @ PromptingTools [/🤫/PromptingTools.jl/src/llm_google.jl:180](https://file+.vscode-resource.vscode-cdn.net/🤫/PromptingTools.jl/src/llm_google.jl:180)
AIMessage("Hi there! I'm here to help you with any questions or tasks you may have. Just let me know what's on your mind, and I'll do my best to assist you.")
```

Looking forward to hear your opinion on this.

### CODE REVIEW

**Comment by svilupp** [comment]
Thanks for the issue! 

I've realized that I forgot to update the tutorial in the docs -- I've done so now. There is a small section on the workaround.

The problem is that GoogleGenAI is not registered, so while the extension exists in our codebase, we cannot automatically load it because Julia doesn't recognize the package.

You're right that we don't actually _need_ the package and could hack our way around, but I'd prefer to use the available packages where possible as it helps to distribute the maintenance effort across the community.

Let's see what the package author says - if he's not keen to register the package, perhaps we should go ahead with your solution to provide support for Google models.

**Comment by svilupp** [comment]
Looping in the registration work for GoogleGenAI: https://github.com/tylerjthomas9/GoogleGenAI.jl/pull/6

**Comment by tylerjthomas9** [comment]
GoogleGenAI.jl is now in the general registry

**Comment by svilupp** [comment]
I'd like to propose closing this PR. I've re-enabled the existing extension now that the package is registered.

@Muhammad-saad-2000 , if you're interested pushing this integration forward, I've opened a small feature request: https://github.com/tylerjthomas9/GoogleGenAI.jl/issues/9 (it should be 10mins of work).

In addition, I've create an issue to bring also the google embedding functionality [details here](https://github.com/svilupp/PromptingTools.jl/issues/112).

**Pull request closed without merging**
