### PR TITLE
A little README.md correction

### PR DESCRIPTION
**Pull request by Muhammad-saad-2000**
The aforementioned correction in #106

### CODE REVIEW

**Comment by svilupp** [comment]
Hi Muhammad! thank you for the PR!

Apologies for not engaging with it sooner. I thought there was some typo in the README, but the correction you're suggesting is not necessary I believe.

Have you tried `using Pkg; Pkg.add("PromptingTools")` ? Did it not work for you? Because it does work for me.

Julia packages are often referred to with the `.jl` suffix, but you don't have to use it when referring to them / importing them / adding them.

Or is your experience different?

**Comment by svilupp** [comment]
As an example, your correction would actually lead to an error:
```julia
julia> Pkg.add("PromptingTools.jl")
ERROR: `PromptingTools.jl` is not a valid package name. Perhaps you meant `PromptingTools`
```

**Comment by Muhammad-saad-2000** [comment]
Hello, it is my pleasure to contribute to this repository.

I believe there is a miss understanding regarding my pull request. The current state of the README mentions `Pkg.add("PromptingTools.jl")` **not** `Pkg.add("PromptingTools")`, and that is what my PR is correcting.

You can double check that from the current README.md (the main page).

**Comment by svilupp** [comment]
Ha! good catch - thank you!

**Pull request merged**
